version: 0.0
os: linux
files:
  - source: target/java-calc-1.0.0.jar
    destination: /home/ec2-user/app
  - source: scripts/start_server.sh
    destination: /home/ec2-user/app/scripts

hooks:
  BeforeInstall:
    - location: scripts/install_java.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
