version: 0.2

env:
  variables:
    S3_BUCKET: "my-devops-sonarless-reports"

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Running Maven build and site generation..."
      - mvn clean install site

  post_build:
    commands:
      - echo "Uploading reports to S3..."
      - aws s3 cp target/site/ s3://$S3_BUCKET/analysis-reports/$CODEBUILD_BUILD_ID/ --recursive
      - echo "Reports uploaded successfully!"

artifacts:
  files:
    # This includes the reports for the pipeline artifact store
    - 'target/site/**/*'
    # This is the application JAR for the CodeDeploy stage
    - 'target/java-calc-1.0.0.jar'
    - 'appspec.yml'
    - 'scripts/**/*'